server:
  port: 8083

spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
